In [1]:
import pandas as pd
import numpy as np

In [4]:
sms=pd.read_csv("E:\\itsstudytym\\assignments\\Naive Bayes\\sms_raw_NB.csv",encoding="ISO-8859-1")
sms.head()

type                                               text
0   ham  Hope you are having a good week. Just checking in
1   ham                            K..give back my thanks.
2   ham        Am also doing in cbe only. But have to pay.
3  spam  complimentary 4 STAR Ibiza Holiday or å£10,000...
4  spam  okmail: Dear Dave this is your final notice to...

In [5]:
sms.groupby('type').describe()

text                                                               
     count unique                                                top freq
type                                                                     
ham   4812   4503                             Sorry, I'll call later   30
spam   747    653  Please call our customer service representativ...    4

In [6]:
sms['ham']=sms['type'].apply(lambda x: 1 if x=='ham' else 0)
sms.head()

type                                               text  ham
0   ham  Hope you are having a good week. Just checking in    1
1   ham                            K..give back my thanks.    1
2   ham        Am also doing in cbe only. But have to pay.    1
3  spam  complimentary 4 STAR Ibiza Holiday or å£10,000...    0
4  spam  okmail: Dear Dave this is your final notice to...    0

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X_train, X_test, y_train, y_test = train_test_split(sms['text'], sms['ham'], test_size=0.3, random_state=50)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()
X_train_count=v.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [10]:
from sklearn.naive_bayes import MultinomialNB

In [11]:
MNB=MultinomialNB()

In [12]:
MNB.fit(X_train_count,y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [13]:
X_test_count=v.transform(X_test)

In [15]:
y_pred=MNB.predict(X_test_count)

In [16]:
y_pred

array([0, 1, 1, ..., 0, 1, 1], dtype=int64)

In [17]:
MNB.score(X_test_count,y_test)

0.9856115107913669

In [20]:
email={"Hello Tony, You recieve a 20% discount"}
email_count=v.transform(email)
MNB.predict(email_count)

array([0], dtype=int64)